version: "3.8"

services:
  # Backend API (Development)
  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile.dev
    environment:
      NODE_ENV: development
      PORT: 3001
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/crypto_exchange
    volumes:
      - ./apps/backend:/app
      - /app/node_modules
    command: bun run dev

  # Frontend Web App (Development)
  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile.dev
    environment:
      NODE_ENV: development
      PORT: 3000
      NEXT_PUBLIC_API_URL: http://localhost:3001
    volumes:
      - ./apps/frontend:/app
      - /app/node_modules
      - /app/.next
    command: bun run dev
