name: production
url: https://crypto-exchange.example.com
deployment_branch_policy:
  protected_branches: true
  custom_branch_policies: false
environment:
  protection_rules:
    - type: required_reviewers
      required_reviewers:
        - "@organization/production-approvers"
        - "@organization/security-team"
    - type: wait_timer
      wait_timer: 15
    - type: prevent_self_review
      enabled: true
secrets:
  - name: DATABASE_URL
    required: true
  - name: KUBE_CONFIG
    required: true
  - name: TELEGRAM_BOT_TOKEN
    required: true
  - name: TELEGRAM_CHAT_ID
    required: true
