name: staging
url: https://staging.crypto-exchange.example.com
deployment_branch_policy:
  protected_branches: false
  custom_branch_policies: true
  custom_branches:
    - develop
    - master
environment:
  protection_rules:
    - type: required_reviewers
      required_reviewers:
        - "@organization/staging-approvers"
    - type: wait_timer
      wait_timer: 5
secrets:
  - name: DATABASE_URL
    required: true
  - name: KUBE_CONFIG
    required: true
  - name: TELEGRAM_BOT_TOKEN
    required: true
  - name: TELEGRAM_CHAT_ID
    required: true
