name: Cleanup Container Registry

on:
  schedule:
    # Run every Sunday at 2 AM UTC
    - cron: "0 2 * * 0"
  workflow_dispatch:
    inputs:
      keep_versions:
        description: "Number of versions to keep"
        required: false
        default: "10"
        type: string

env:
  REGISTRY: ghcr.io

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Cleanup API package versions
        uses: actions/delete-package-versions@v4
        with:
          package-name: ${{ github.repository }}/api
          package-type: container
          min-versions-to-keep: ${{ github.event.inputs.keep_versions || '10' }}
          delete-only-untagged-versions: true
          ignore-versions: '^(latest|main|master|v\d+\.\d+\.\d+)$'

      - name: Cleanup Web package versions
        uses: actions/delete-package-versions@v4
        with:
          package-name: ${{ github.repository }}/web
          package-type: container
          min-versions-to-keep: ${{ github.event.inputs.keep_versions || '10' }}
          delete-only-untagged-versions: true
          ignore-versions: '^(latest|main|master|v\d+\.\d+\.\d+)$'

      - name: Cleanup Summary
        run: |
          echo "## Cleanup Summary" >> $GITHUB_STEP_SUMMARY
          echo "- **Versions Kept**: ${{ github.event.inputs.keep_versions || '10' }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Protected Tags**: latest, main, master, v*.*.* (semantic versions)" >> $GITHUB_STEP_SUMMARY
          echo "- **Cleanup Target**: Untagged and old PR/branch versions" >> $GITHUB_STEP_SUMMARY
